---
nerdfont_urls:
  - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
  - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Noto.zip

apps:
  - bat
  - fzf
  - git
  - go
  - sqlite
  - node
  - ssh-copy-id
  - openssl
  - wget
  - zsh

gui_apps:
  - docker
  - firefox
  - handbrake
  - discord
  - obsidian
  - spotify
#  - davinciresolve
  - obs
  - prismlauncher

linux_only_apps:
  - fastfetch

brew_only_apps:
  - nano
  - oh-my-posh
  - openjdk

homebrew_cask_appdir: /Applications
brew_cask_apps:
  - microsoft-edge

linux_apps: "{{ linux_only_apps }}"

homebrew_installed_packages: "{{ apps + brew_only_apps }}"
homebrew_cask_apps: "{{ gui_apps + brew_cask_apps }}"
homebrew_cask_accept_external_apps: true
homebrew_upgrade_all_packages: true

mas_installed_apps:
