---
- name: Remove Leftover OMP Files
  block:
    - name: Find omp.cache files
      find:
        paths: "{{ ansible_env.HOME }}"
        patterns: omp.cache*
      register: omp_files

    - name: Clear omp.cache files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ omp_files.files }}"

    - name: Remove the themes directory
      file:
        path: "{{ ansible_env.HOME }}/themes"
        state: absent
        recurse: yes
